const LOGIN_BY_SHANECT = "LOGIN_BY_SHANECT"
const LOGIN_BY_FACEBOOK = "LOGIN_BY_FACEBOOK"
const LOGIN_BY_GOOGLE = "LOGIN_BY_GOOGLE"
const REMEMBER_PASSWORD = "REMEMBER_PASSWORD"
const CHOOSE_LOGIN_TYPE = "CHOOSE_LOGIN_TYPE"

export default {
    LOGIN_BY_FACEBOOK,
    LOGIN_BY_GOOGLE,
    LOGIN_BY_SHANECT,
    REMEMBER_PASSWORD,
    CHOOSE_LOGIN_TYPE,
}