const LOGIN_BY_SHANECT = "LOGIN_BY_SHANECT"
const LOGIN_BY_FACEBOOK = "LOGIN_BY_FACEBOOK"
const LOGIN_BY_GOOGLE = "LOGIN_BY_GOOGLE"
const REMEMBER_PASSWORD = "REMEMBER_PASSWORD"
const CHOOSE_LOGIN_TYPE = "CHOOSE_LOGIN_TYPE"
const CLOSE_LOGIN_FORM = "CLOSE_LOGIN_FORM"
const SET_TEXT_USERNAME = "SET_TEXT_USERNAME"
const SET_TEXT_PASSWORD = "SET_TEXT_PASSWORD"
const CHOOSE_GENDER = "CHOOSE_GENDER"
const CHANGE_FULL_NAME = "CHANGE_FULL_NAME"
const CHANGE_USERNAME = "CHANGE_USER_NAME"
const CHANGE_EMAIL = "CHANGE_EMAIL"
const CHANGE_PASSWORD= "CHANGE_PASSWORD"

export default {
    LOGIN_BY_FACEBOOK,
    LOGIN_BY_GOOGLE,
    LOGIN_BY_SHANECT,
    REMEMBER_PASSWORD,
    CHOOSE_LOGIN_TYPE,
    CLOSE_LOGIN_FORM,
    SET_TEXT_USERNAME,
    SET_TEXT_PASSWORD,
    CHOOSE_GENDER,
    CHANGE_FULL_NAME,
    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    CHANGE_EMAIL,
}