const LOGIN_BY_SHANECT = "LOGIN_BY_SHANECT"
const LOGIN_BY_FACEBOOK = "LOGIN_BY_FACEBOOK"
const LOGIN_BY_GOOGLE = "LOGIN_BY_GOOGLE"
const REMEMBER_PASSWORD = "REMEMBER_PASSWORD"
const CHOOSE_LOGIN_TYPE = "CHOOSE_LOGIN_TYPE"
const CLOSE_LOGIN_FORM = "CLOSE_LOGIN_FORM"
const SET_TEXT_USERNAME = "SET_TEXT_USERNAME"
const SET_TEXT_PASSWORD = "SET_TEXT_PASSWORD"
const CHOOSE_GENDER = "CHOOSE_GENDER"
const CHANGE_FULL_NAME = "CHANGE_FULL_NAME"
const CHANGE_USERNAME = "CHANGE_USER_NAME"
const CHANGE_EMAIL = "CHANGE_EMAIL"
const CHANGE_PASSWORD= "CHANGE_PASSWORD"
const SHOW_IMAGE_MODAL = 'SHOW_IMAGE_MODAL'
const CLOSE_IMAGE_MODAL = 'CLOSE_IMAGE_MODAL'
const INIT_FILTER_HEIGHT = 'GET_FILTER_HEIGHT'
const ON_SCROLL_Y = 'ON_SCROLL_Y'
const ON_CLICK_DETAIL_FILTER ='ON_CLICK_DETAIL_FILTER'
const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
const SELECT_CATEGORY = 'SELECT_CATEGORY'
const CHECK_SUBCATEGORY = 'CHECK_SUB_CATEGORY'

export default {
    LOGIN_BY_FACEBOOK,
    LOGIN_BY_GOOGLE,
    LOGIN_BY_SHANECT,
    REMEMBER_PASSWORD,
    CHOOSE_LOGIN_TYPE,
    CLOSE_LOGIN_FORM,
    SET_TEXT_USERNAME,
    SET_TEXT_PASSWORD,
    CHOOSE_GENDER,
    CHANGE_FULL_NAME,
    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    CHANGE_EMAIL,
    SHOW_IMAGE_MODAL,
    CLOSE_IMAGE_MODAL,
    INIT_FILTER_HEIGHT,
    ON_SCROLL_Y,
    ON_CLICK_DETAIL_FILTER,
    FETCH_CATEGORIES,
    SELECT_CATEGORY,
    CHECK_SUBCATEGORY,
}